### PR TITLE
Fix incorrectly formatted 'amount' variables

### PR DESCRIPTION
**Pull request by zestyr**
Fixes lbryio/lbry#588, goes with lbryio/lbryschema#12 and lbryio/lbry#757.
It seemed like the transition from float to decimal wasn't complete, so I did that as well.
I've run the tests, resolved channels and claims, published, etc. and everything works as expected. All amount fields are now formatted as decimal.

### CODE REVIEW

**Comment by zestyr** [comment]
Travis complains about this:
```
        out = commands.format_amount_value(a)
>       self.assertEqual(1.0, out['amount'])
E       AssertionError: 1.0 != '1'
```

Is there something I'm missing that would break because of this change?

**Comment by kaykurokawa** [comment]
Let's change that test. 

I don't think it'll break lbryum , but probably there might be stuff in lbrynet that will. 

We'll need to run integation testing on this with https://github.com/lbryio/lbry-in-a-box. Please install it (follow README instructions) on your machine and try running the tests with your patch.

**Comment by zestyr** [comment]
I've run the integration test a few times, but keep getting the following error. Nothing fails when running my patch.
```
Running:_test_publish
E
======================================================================
ERROR: test_lbrynet (__main__.LbrynetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_testing.py", line 33, in test_lbrynet
    self._test_publish('testname', claim_amount=1, )
  File "/home/zed/src/dev/lbry/lbry-in-a-box/test_utils.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "integration_testing.py", line 304, in _test_publish
    out = lbrynets['lbrynet'].claim_show({'name': claim_name})
  File "/home/zed/src/dev/lbry/lbry-env/lib/python2.7/site-packages/jsonrpc/proxy.py", line 176, in __call__
    respdata = self._post(url, postdata).read()
  File "/home/zed/src/dev/lbry/lbry-env/lib/python2.7/site-packages/jsonrpc/proxy.py", line 169, in _post
    return self._opener.open(url, data)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

Skipping that test, I get this error.
```
Running:_test_support
E
======================================================================
ERROR: test_lbrynet (__main__.LbrynetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "integration_testing.py", line 38, in test_lbrynet
    self._test_support()
  File "/home/zed/src/dev/lbry/lbry-in-a-box/test_utils.py", line 109, in wrapper
    return func(*args, **kwargs)
  File "integration_testing.py", line 541, in _test_support
    self.assertEqual(claim_name, out['claim']['name'])
TypeError: 'bool' object has no attribute '__getitem__'

----------------------------------------------------------------------
```

The rest of the tests pass.
I'll investigate tomorrow. I think I know what causes the first one, but I don't understand the second error.

**Comment by jackrobison** [comment]
Merged here: https://github.com/lbryio/lbryum/commit/e47d05f72ca95a630065da2038f6349c0ee22fee

**Pull request closed without merging**
