### PR TITLE
changing imports to import from file not lbryum

### PR DESCRIPTION
**Pull request by kaykurokawa**
pull request for https://github.com/lbryio/lbryum/issues/21

### CODE REVIEW

**Comment by kaykurokawa** [comment]
adding f0bb526 which fixes and adds unit tests for lbryum

**Comment by jackrobison** [comment]
👍

**Comment by jobevers** [comment]
for the first commit - absolute imports are preferred over relative ones: "Do not use relative names in imports. Even if the module is in the same package, use the full package name."

**Comment by kaykurokawa** [comment]
I think we should stick to what the rest of lbryum does even though its less pythonic. Mixing up styles is worse than using relative imports IMO.

The main reason I fixed this is that the absolute imports breaks the unittests because they don't import lib as lbryum.

**Pull request merged**
