### PR TITLE
Store certificate claims

### PR DESCRIPTION
**Pull request by jackrobison**
Store certificate claims if the private key is in the wallet

### CODE REVIEW

**Comment by lyoshenka** [comment]
Jack, what's the next step on this?

**Comment by lyoshenka** [comment]
Next steps: several days of work, bump lbryum server

**Comment by eukreign** [comment]
@jackrobison @lyoshenka can we add finishing this PR to planning session today?

**Comment by jackrobison** [comment]
I don't think this would be terribly useful at this point, we can revisit if this changes.

**Pull request closed without merging**
