### PR TITLE
Fix CoinChooserOldestFirst to select oldest coins

### PR DESCRIPTION
**Pull request by hackrush01**

### CODE REVIEW

**Comment by kaykurokawa** [comment]
Is there a reason why you need this change ? Here is the docstring for CoinChooserOldestFirst 

    '''Maximize transaction priority. Select the oldest unspent
    transaction outputs in your wallet, that are sufficient to cover
    the spent amount. Then, remove any unneeded inputs, starting with
    the smallest in value.
    '''

So the original code does exactly what's described here. The advantage here is that there's some priority assigned to keeping the transaction smaller by removing the smallest inputs.

**Comment by hackrush01** [comment]
The reason to do that is to prevent the starvation condition in which smaller and older coins may never be selected. This ensures that those coins are cleared out, albeit at the cost of bigger transaction size.

**Comment by hackrush01** [comment]
Should I close this PR then?

**Comment by kaykurokawa** [comment]
thought about it a bit more:  Here is what we actually need to do: 

If our actual goal is to prioritize small unspents, which would be a good thing for our application (some of our apps create a lot of small transactions resulting in a lot of small unspents), we could create a new CoinChooser which does that and just ignores coin age (how old the unspent is), and use it instead.  

Transaction priority is not really a thing anymore since Bitcoin Core version 0.12 ( lbrycrdd is > 0.12 ) (see https://github.com/bitcoin/bitcoin/pull/7022 for more information ) so giving priority to coin age (returning the oldest coin) doesn't make sense anymore. Current upstream electrum version completely removed CoinchooserOldestFirst and uses the privacy chooser.

**Comment by lyoshenka** [comment]
amit, why did you want to make this change? is there a bug that's being
fixed, or poor performance, or something else?

**Comment by hackrush01** [comment]
I did it mainly because I noticed the inconsistency, and it helps solve the starvation problem that was described above.

**Comment by hackrush01** [comment]
Closed. New proper issue is #221

**Pull request closed without merging**
